// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/alyyousuf7/goserver/model"
	mock "github.com/stretchr/testify/mock"
)

// ClientStorer is an autogenerated mock type for the ClientStorer type
type ClientStorer struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *ClientStorer) AddUser(_a0 model.Client, _a1 model.User, _a2 model.ClientRole) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Client, model.User, model.ClientRole) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: _a0
func (_m *ClientStorer) Create(_a0 *model.Client) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Client) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOne provides a mock function with given fields: where
func (_m *ClientStorer) FindOne(where ...interface{}) (*model.Client, error) {
	var _ca []interface{}
	_ca = append(_ca, where...)
	ret := _m.Called(_ca...)

	var r0 *model.Client
	if rf, ok := ret.Get(0).(func(...interface{}) *model.Client); ok {
		r0 = rf(where...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(where...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
