// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/alyyousuf7/goserver/model"
	mock "github.com/stretchr/testify/mock"
)

// UserStorer is an autogenerated mock type for the UserStorer type
type UserStorer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *UserStorer) Create(_a0 *model.User) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOne provides a mock function with given fields: where
func (_m *UserStorer) FindOne(where ...interface{}) (*model.User, error) {
	var _ca []interface{}
	_ca = append(_ca, where...)
	ret := _m.Called(_ca...)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(...interface{}) *model.User); ok {
		r0 = rf(where...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(where...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
